### ISSUE TITLE
Attribute reference to 'bigwig' on Sample in chipseq.py

### ISSUE THREAD

**Issue by vreuter** [epigen/open_pipelines#4]
In the `chipseq.py` pipeline, there are three usages of `sample.bigwig`, but the `Sample` instance being used does not have a `bigwig` attribute.
```
Target exists: `/sfs/lustre/allocations/shefflab/processed//kipnis_chip/micro/results_pipeline/input_12k/mapped/input_12k.trimmed.bowtie2.filtered.bam.bai`
Removed existing flag: /sfs/lustre/allocations/shefflab/processed//kipnis_chip/micro/results_pipeline/input_12k/chipseq_failed.flag
Traceback (most recent call last):
  File "/home/vpr9v/code/open_pipelines/pipelines/chipseq.py", line 757, in <module>
    sys.exit(main())
  File "/home/vpr9v/code/open_pipelines/pipelines/chipseq.py", line 484, in main
    process(sample, pipe_manager, args)
  File "/home/vpr9v/code/open_pipelines/pipelines/chipseq.py", line 642, in process
    track_dir = os.path.dirname(sample.bigwig)
AttributeError: 'ChIPseqSample' object has no attribute 'bigwig'

Pypiper terminating spawned child process 190059

Change status from running to failed
```

**Comment by nsheff** [comment]
@afrendeiro where did we lose the `bigwig` attribute?

**Comment by vreuter** [comment]
This is added now.

**Comment by vreuter** [comment]
Actually, this is just solved in the `databio` fork...
